name: Feature Request
description: Suggest a new role, add-on, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What kind of addition?
      options:
        - New role
        - New add-on / knowledge base
        - Template improvement
        - Router / navigation improvement
        - Platform adaptation (GPT, API, etc.)
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to see?
      placeholder: Describe your idea
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What problem does this solve?
    validations:
      required: false
