name: Question
description: Ask about architecture, setup, or adaptation
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Questions are welcome! For faster response, you can also reach out via [Telegram](https://t.me/vangogishe).

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What's your question about?
      options:
        - Architecture / how it works
        - Building my own bot
        - Adapting to another platform
        - Knowledge Base / Router setup
        - Brandbook integration
        - Role interaction / REQUEST format
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Ask away
    validations:
      required: true
